<a href="https://colab.research.google.com/github/SajenMurali/Mini-project/blob/main/Mini_Project_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# load dataset
df = pd.read_csv("data - Sheet1.csv")

# create target variable
df['Target'] = df['SleepQuality'].apply(lambda x: 0 if x <= 3 else 1)

# view result
df[['SleepQuality', 'Target']].head()

SleepQuality  Target
0           3.0       0
1           4.0       1
2           4.0       1
3           4.0       1
4           3.0       0

In [ ]:
df.head()

Bedtime  bed(minutes) Wakeuptime\n  wakeup(minutes) wakeup(adjusted)  \
0   00:19          19.0        06:41            401.0           401.00   
1   00:30          30.0        07:00            420.0           420.00   
2   23:30        1410.0        06:30            390.0         1,830.00   
3   00:36          36.0        08:32            512.0           512.00   
4   00:57          57.0        08:41            521.0           521.00   

  ScreenTime  ScreenTime (Total Hours)  Unlocks  SleepQuality  \
0      04:35                      4.58     32.0           3.0   
1      04:46                      4.77    184.0           4.0   
2      07:30                      7.50     78.0           4.0   
3      06:05                      6.08     44.0           4.0   
4      09:27                      9.45      6.0           3.0   

  SocialMediaUsage  SocialMediaUsage (minutes)  sleep duration hours   Target  
0            04:41                       281.0                  382.0       0  
1            02:30                       150.0                  390.0       1  
2            06:35                       395.0                  420.0       1  
3            03:32                       212.0                  476.0       1  
4            07:42                       462.0                  464.0       0

In [ ]:
# rename column for clarity (recommended)
df.rename(columns={'sleep duration hours ': 'SleepDuration_min'}, inplace=True)

In [ ]:
# create categorical target based on sleep duration
def sleep_duration_category(x):
    if x >= 420:
        return 2   # Good sleep
    elif x >= 360:
        return 1   # Moderate sleep
    else:
        return 0   # Poor sleep

df['SleepDuration_Target'] = df['SleepDuration_min'].apply(sleep_duration_category)

# view result
df[['SleepDuration_min', 'SleepDuration_Target']].head()

SleepDuration_min  SleepDuration_Target
0              382.0                     1
1              390.0                     1
2              420.0                     2
3              476.0                     2
4              464.0                     2

In [ ]:
df.head()

Bedtime  bed(minutes) Wakeuptime\n  wakeup(minutes) wakeup(adjusted)  \
0   00:19          19.0        06:41            401.0           401.00   
1   00:30          30.0        07:00            420.0           420.00   
2   23:30        1410.0        06:30            390.0         1,830.00   
3   00:36          36.0        08:32            512.0           512.00   
4   00:57          57.0        08:41            521.0           521.00   

  ScreenTime  ScreenTime (Total Hours)  Unlocks  SleepQuality  \
0      04:35                      4.58     32.0           3.0   
1      04:46                      4.77    184.0           4.0   
2      07:30                      7.50     78.0           4.0   
3      06:05                      6.08     44.0           4.0   
4      09:27                      9.45      6.0           3.0   

  SocialMediaUsage  SocialMediaUsage (minutes)  SleepDuration_min  Target  \
0            04:41                       281.0              382.0       0   
1            02:30                       150.0              390.0       1   
2            06:35                       395.0              420.0       1   
3            03:32                       212.0              476.0       1   
4            07:42                       462.0              464.0       0   

   SleepDuration_Target  
0                     1  
1                     1  
2                     2  
3                     2  
4                     2

In [ ]:
# save modified dataset
df.to_csv("sleep_dataset_modified.csv", index=False)

In [ ]:
data=pd.read_csv("sleep_dataset_modified.csv")
data.head()

Bedtime  bed(minutes) Wakeuptime\n  wakeup(minutes) wakeup(adjusted)  \
0   00:19          19.0        06:41            401.0           401.00   
1   00:30          30.0        07:00            420.0           420.00   
2   23:30        1410.0        06:30            390.0         1,830.00   
3   00:36          36.0        08:32            512.0           512.00   
4   00:57          57.0        08:41            521.0           521.00   

  ScreenTime  ScreenTime (Total Hours)  Unlocks  SleepQuality  \
0      04:35                      4.58     32.0           3.0   
1      04:46                      4.77    184.0           4.0   
2      07:30                      7.50     78.0           4.0   
3      06:05                      6.08     44.0           4.0   
4      09:27                      9.45      6.0           3.0   

  SocialMediaUsage  SocialMediaUsage (minutes)  SleepDuration_min  Target  \
0            04:41                       281.0              382.0       0   
1            02:30                       150.0              390.0       1   
2            06:35                       395.0              420.0       1   
3            03:32                       212.0              476.0       1   
4            07:42                       462.0              464.0       0   

   SleepDuration_Target  
0                     1  
1                     1  
2                     2  
3                     2  
4                     2

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
# create screentime in minutes
data['screentime_min'] = data['ScreenTime (Total Hours)'] * 60

# optional: round
data['screentime_min'] = data['screentime_min'].round(0)

data[['ScreenTime (Total Hours)', 'screentime_min']].head()


ScreenTime (Total Hours)  screentime_min
0                      4.58           275.0
1                      4.77           286.0
2                      7.50           450.0
3                      6.08           365.0
4                      9.45           567.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 347 entries, 0 to 346
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Bedtime                     99 non-null     object 
 1   bed(minutes)                99 non-null     float64
 2   Wakeuptime
                 99 non-null     object 
 3   wakeup(minutes)             99 non-null     float64
 4   wakeup(adjusted)            99 non-null     object 
 5   ScreenTime                  99 non-null     object 
 6   ScreenTime (Total Hours)    99 non-null     float64
 7   Unlocks                     99 non-null     float64
 8   SleepQuality                99 non-null     float64
 9   SocialMediaUsage            99 non-null     object 
 10  SocialMediaUsage (minutes)  187 non-null    float64
 11  SleepDuration_min           347 non-null    float64
 12  Target                      347 non-null    int64  
 13  SleepDuration_Target        347 non

In [ ]:
data.shape

(347, 15)

In [ ]:
data.head()

Bedtime  bed(minutes) Wakeuptime\n  wakeup(minutes) wakeup(adjusted)  \
0   00:19          19.0        06:41            401.0           401.00   
1   00:30          30.0        07:00            420.0           420.00   
2   23:30        1410.0        06:30            390.0         1,830.00   
3   00:36          36.0        08:32            512.0           512.00   
4   00:57          57.0        08:41            521.0           521.00   

  ScreenTime  ScreenTime (Total Hours)  Unlocks  SleepQuality  \
0      04:35                      4.58     32.0           3.0   
1      04:46                      4.77    184.0           4.0   
2      07:30                      7.50     78.0           4.0   
3      06:05                      6.08     44.0           4.0   
4      09:27                      9.45      6.0           3.0   

  SocialMediaUsage  SocialMediaUsage (minutes)  SleepDuration_min  Target  \
0            04:41                       281.0              382.0       0   
1            02:30                       150.0              390.0       1   
2            06:35                       395.0              420.0       1   
3            03:32                       212.0              476.0       1   
4            07:42                       462.0              464.0       0   

   SleepDuration_Target  screentime_min  
0                     1           275.0  
1                     1           286.0  
2                     2           450.0  
3                     2           365.0  
4                     2           567.0

In [ ]:
print("Initial shape:", data.shape)

# -------------------------------
# 2. RENAME COLUMNS (CLEAN NAMES)
# -------------------------------
data.columns = data.columns.str.strip().str.replace(" ", "_").str.lower()

# Explicit renaming for clarity
data.rename(columns={
    'bed(minutes)': 'bedtime_min',
    'wakeup(adjusted)': 'wakeup_min'
}, inplace=True)

# -------------------------------
# 3. HANDLE MISSING VALUES
# -------------------------------
num_cols = data.select_dtypes(include=['int64', 'float64']).columns
data[num_cols] = data[num_cols].fillna(data[num_cols].median())

# -------------------------------
# 4. REMOVE DUPLICATES
# -------------------------------
data.drop_duplicates(inplace=True)

# -------------------------------
# 5. REMOVE INVALID SLEEP RECORDS
# -------------------------------
data = data[(data['sleepduration_min'] >= 120) & (data['sleepduration_min'] <= 720)]

# -------------------------------
# 6. CREATE TARGET VARIABLE
# -------------------------------
if 'target' not in data.columns:
    data['target'] = data['sleepquality'].apply(lambda x: 0 if x <= 3 else 1)

# -------------------------------
# 9. FEATURE SCALING
# -------------------------------
features_to_scale = [
    'screentime_min',
    'socialmediausage_(minutes)',
    'unlocks',
    'sleepduration_min'
]

scaler = StandardScaler()
data[features_to_scale] = scaler.fit_transform(data[features_to_scale])

# -------------------------------
# 10. FINAL CHECK
# -------------------------------
print("Final shape:", data.shape)
print(data.head())
print(data.info())

# -------------------------------
# 11. SAVE FILE
# -------------------------------
data.to_csv("sleep_dataset_cleaned_preprocessed.csv", index=False)

print("✅ Dataset cleaned and saved successfully!")


Initial shape: (347, 15)
Final shape: (98, 15)
  bedtime  bedtime_min wakeuptime  wakeup(minutes) wakeup_min screentime  \
0   00:19         19.0      06:41            401.0     401.00      04:35   
1   00:30         30.0      07:00            420.0     420.00      04:46   
2   23:30       1410.0      06:30            390.0   1,830.00      07:30   
3   00:36         36.0      08:32            512.0     512.00      06:05   
4   00:57         57.0      08:41            521.0     521.00      09:27   

   screentime_(total_hours)   unlocks  sleepquality socialmediausage  \
0                      4.58 -0.938607           3.0            04:41   
1                      4.77  2.754338           4.0            02:30   
2                      7.50  0.178995           4.0            06:35   
3                      6.08 -0.647059           4.0            03:32   
4                      9.45 -1.570295           3.0            07:42   

   socialmediausage_(minutes)  sleepduration_min  target  \
0  

In [ ]:
# FEATURES & TARGET
X1 = data[
    [
        'screentime_min',
        'socialmediausage_(minutes)',
        'unlocks'
    ]
]

y1 = data['target']

# keep only numeric columns
X1 = X1.select_dtypes(include=['int64', 'float64'])

# split
from sklearn.model_selection import train_test_split
X1_train, X1_test, y1_train, y1_test = train_test_split(
    X1, y1, test_size=0.2, random_state=42, stratify=y1
)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

rf1 = RandomForestClassifier(n_estimators=100, random_state=42)
rf1.fit(X1_train, y1_train)

y1_pred = rf1.predict(X1_test)

print("Accuracy:", accuracy_score(y1_test, y1_pred))
print("Confusion Matrix:\n", confusion_matrix(y1_test, y1_pred))


Accuracy: 0.45
Confusion Matrix:
 [[4 5]
 [6 5]]


In [ ]:
print(y1.value_counts())

target
1    52
0    46
Name: count, dtype: int64


In [ ]:
from sklearn.model_selection import cross_val_score

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=6,
    class_weight='balanced',
    random_state=42
)

scores = cross_val_score(rf, X1, y1, cv=5, scoring='accuracy')
print("CV Accuracy:", scores)
print("Mean Accuracy:", scores.mean())


CV Accuracy: [0.4        0.4        0.5        0.63157895 0.47368421]
Mean Accuracy: 0.4810526315789474


In [ ]:
X1.columns


Index(['screentime_min', 'socialmediausage_(minutes)', 'unlocks'], dtype='object')

In [ ]:
X1 = data[
    [
        'screentime_min',
        'socialmediausage_(minutes)',
        'unlocks'
    ]
]

y1 = data['target']


In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=6,
    class_weight='balanced',
    random_state=42
)

scores = cross_val_score(rf, X1, y1, cv=5, scoring='accuracy')
print(scores)
print("Mean CV Accuracy:", scores.mean())


[0.4        0.4        0.5        0.63157895 0.47368421]
Mean CV Accuracy: 0.4810526315789474


In [ ]:
# Clean feature set (no leakage)
X_ann = data[['screentime_min', 'socialmediausage_(minutes)', 'unlocks']]
y_ann = data['target']


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_ann, y_ann,
    test_size=0.2,
    random_state=42,
    stratify=y_ann
)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

ann = Sequential([
    Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(8, activation='relu'),
    Dense(1, activation='sigmoid')
])

ann.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = ann.fit(
    X_train, y_train,
    epochs=50,
    batch_size=8,
    validation_split=0.2,
    verbose=1
)


C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 3s 107ms/step - accuracy: 0.5161 - loss: 0.7211 - val_accuracy: 0.5625 - val_loss: 0.6829
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.5323 - loss: 0.7153 - val_accuracy: 0.5625 - val_loss: 0.6839
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.5000 - loss: 0.7107 - val_accuracy: 0.5000 - val_loss: 0.6861
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.4677 - loss: 0.7047 - val_accuracy: 0.4375 - val_loss: 0.6888
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.4677 - loss: 0.7000 - val_accuracy: 0.3750 - val_loss: 0.6912
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 1s 36ms/step - accuracy: 0.5161 - loss: 0.6960 - val_accuracy: 0.3750 - val_loss: 0.6932
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5645 - loss: 0.6928 - val_accuracy: 0.5000 - val_loss: 0.6966
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5968 - loss: 0.6887 - val_accuracy: 0.5000 - val_loss: 0.6998

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

y_pred_ann = (ann.predict(X_test) > 0.5).astype(int).flatten()

print("ANN Accuracy:", accuracy_score(y_test, y_pred_ann))
print("ANN Confusion Matrix:\n", confusion_matrix(y_test, y_pred_ann))
print("ANN Classification Report:\n",
      classification_report(y_test, y_pred_ann))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step
ANN Accuracy: 0.6
ANN Confusion Matrix:
 [[ 1  8]
 [ 0 11]]
ANN Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.11      0.20         9
           1       0.58      1.00      0.73        11

    accuracy                           0.60        20
   macro avg       0.79      0.56      0.47        20
weighted avg       0.77      0.60      0.49        20



In [ ]:
from sklearn.model_selection import KFold
import numpy as np

kf = KFold(n_splits=5, shuffle=True, random_state=42)
ann_cv_acc = []

for train_idx, test_idx in kf.split(X_ann):
    X_tr, X_te = X_ann.iloc[train_idx], X_ann.iloc[test_idx]
    y_tr, y_te = y_ann.iloc[train_idx], y_ann.iloc[test_idx]

    model = Sequential([
        Dense(16, activation='relu', input_shape=(X_tr.shape[1],)),
        Dense(8, activation='relu'),
        Dense(1, activation='sigmoid')
    ])

    model.compile(
        optimizer=Adam(0.001),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    model.fit(X_tr, y_tr, epochs=40, batch_size=8, verbose=0)
    y_pred = (model.predict(X_te) > 0.5).astype(int).flatten()
    ann_cv_acc.append(accuracy_score(y_te, y_pred))

print("ANN CV Accuracies:", ann_cv_acc)
print("Mean ANN CV Accuracy:", np.mean(ann_cv_acc))


C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step


C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step


C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step


C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step


C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step
ANN CV Accuracies: [0.5, 0.4, 0.65, 0.3684210526315789, 0.6842105263157895]
Mean ANN CV Accuracy: 0.5205263157894737


In [ ]:
X_sd = data[['screentime_min', 'socialmediausage_(minutes)', 'unlocks']]
y_sd = data['sleepduration_target']


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_sd, y_sd,
    test_size=0.2,
    random_state=42,
    stratify=y_sd
)


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

rf_sd = RandomForestClassifier(
    n_estimators=300,
    max_depth=6,
    class_weight='balanced',
    random_state=42
)

rf_sd.fit(X_train, y_train)

y_pred_rf = rf_sd.predict(X_test)

print("RF Accuracy (Sleep Duration):", accuracy_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))


RF Accuracy (Sleep Duration): 0.35
Confusion Matrix:
 [[1 1 3]
 [0 0 4]
 [2 3 6]]
              precision    recall  f1-score   support

           0       0.33      0.20      0.25         5
           1       0.00      0.00      0.00         4
           2       0.46      0.55      0.50        11

    accuracy                           0.35        20
   macro avg       0.26      0.25      0.25        20
weighted avg       0.34      0.35      0.34        20



In [ ]:
from sklearn.model_selection import cross_val_score

rf_scores = cross_val_score(
    rf_sd, X_sd, y_sd, cv=5, scoring='accuracy'
)

print("RF CV Accuracies:", rf_scores)
print("Mean RF CV Accuracy:", rf_scores.mean())


RF CV Accuracies: [0.45       0.45       0.5        0.42105263 0.57894737]
Mean RF CV Accuracy: 0.48


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

ann_sd = Sequential([
    Dense(32, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(16, activation='relu'),
    Dense(3, activation='softmax')
])

ann_sd.compile(
    optimizer=Adam(0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

ann_sd.fit(
    X_train, y_train,
    epochs=50,
    batch_size=8,
    validation_split=0.2,
    verbose=1
)


Epoch 1/50


C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


8/8 ━━━━━━━━━━━━━━━━━━━━ 3s 81ms/step - accuracy: 0.6452 - loss: 0.9569 - val_accuracy: 0.3750 - val_loss: 1.1407
Epoch 2/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.6290 - loss: 0.9380 - val_accuracy: 0.5000 - val_loss: 1.1499
Epoch 3/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6129 - loss: 0.9274 - val_accuracy: 0.4375 - val_loss: 1.1599
Epoch 4/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5968 - loss: 0.9169 - val_accuracy: 0.3750 - val_loss: 1.1728
Epoch 5/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.5968 - loss: 0.9066 - val_accuracy: 0.3750 - val_loss: 1.1819
Epoch 6/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5968 - loss: 0.9003 - val_accuracy: 0.3750 - val_loss: 1.1906
Epoch 7/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.5968 - loss: 0.8935 - val_accuracy: 0.3750 - val_loss: 1.1982
Epoch 8/50
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.5968 - loss: 0.8878 - val_accuracy: 0.3750 - val_loss: 1.2053
Epoch 9/50


In [ ]:
import numpy as np

y_pred_ann = ann_sd.predict(X_test).argmax(axis=1)

print("ANN Accuracy (Sleep Duration):", accuracy_score(y_test, y_pred_ann))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_ann))
print(classification_report(y_test, y_pred_ann))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 224ms/step
ANN Accuracy (Sleep Duration): 0.5
Confusion Matrix:
 [[ 0  0  5]
 [ 0  0  4]
 [ 1  0 10]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.00      0.00      0.00         4
           2       0.53      0.91      0.67        11

    accuracy                           0.50        20
   macro avg       0.18      0.30      0.22        20
weighted avg       0.29      0.50      0.37        20



C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", 

In [ ]:
from sklearn.model_selection import KFold

kf = KFold(n_splits=5, shuffle=True, random_state=42)
ann_scores = []

for tr, te in kf.split(X_sd):
    X_tr, X_te = X_sd.iloc[tr], X_sd.iloc[te]
    y_tr, y_te = y_sd.iloc[tr], y_sd.iloc[te]

    model = Sequential([
        Dense(32, activation='relu', input_shape=(X_tr.shape[1],)),
        Dense(16, activation='relu'),
        Dense(3, activation='softmax')
    ])

    model.compile(
        optimizer=Adam(0.001),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    model.fit(X_tr, y_tr, epochs=40, batch_size=8, verbose=0)
    preds = model.predict(X_te).argmax(axis=1)
    ann_scores.append(accuracy_score(y_te, preds))

print("ANN CV Accuracies:", ann_scores)
print("Mean ANN CV Accuracy:", np.mean(ann_scores))


C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step


C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step


C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step


C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step


C:\ProgramData\anaconda3\envs\py3-TF2.0\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
ANN CV Accuracies: [0.45, 0.55, 0.6, 0.3157894736842105, 0.5263157894736842]
Mean ANN CV Accuracy: 0.488421052631579
